# Import the tensorflow lib

In [6]:
import tensorflow as tf

In [7]:
#initialize constants

a=tf.constant([2,4,6,9])
b=tf.constant([5,2,0,2])

print(a)
print(b)

tf.Tensor([2 4 6 9], shape=(4,), dtype=int32)
tf.Tensor([5 2 0 2], shape=(4,), dtype=int32)


In [8]:
#ADD OPERATION

x = [1, 2, 3, 4, 5]
y = 1
p=tf.add(x, y)
print(p)

x = [4,16,44,80]
y = 4
p=tf.divide(x, y)

print(p)

tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)
tf.Tensor([ 1.  4. 11. 20.], shape=(4,), dtype=float64)


In [9]:
print(tf.add(3,57))

tf.Tensor(60, shape=(), dtype=int32)


In [11]:
n=tf.constant([3.3,43,6.5])
print(n)

tf.Tensor([ 3.3 43.   6.5], shape=(3,), dtype=float32)


In [12]:
#GREATER OPERATION

x = tf.constant([5, 4, 6])
y = tf.constant([5, 2, 5])
tf.math.greater(x, y) 

<tf.Tensor: shape=(3,), dtype=bool, numpy=array([False,  True,  True])>

In [13]:
Z = tf.constant([[1, 2],[3, 4], [5, 6]], dtype=tf.float16)
print(Z)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


# Import the numpy lib to perform numperial operations in python

In [14]:
import numpy as np

In [15]:
np.array(Z)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [16]:
Z.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [17]:
a = tf.constant([[7, 2],
                 [3, 9]])
b = tf.constant([[5, 7],
                 [1, 2]])

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")


tf.Tensor(
[[12  9]
 [ 4 11]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[35 14]
 [ 3 18]], shape=(2, 2), dtype=int32) 



In [21]:
 c = tf.zeros([7,8,2,6])

In [22]:
print("Type of every element:", c.dtype)
print("Number of axes:", c.ndim)
print("Shape of tensor:", c.shape)
print("Elements along axis 0 of tensor:", c.shape[0])
print("Elements along the last axis of tensor:", c.shape[-1])
print("Total number of elements: ", tf.size(c).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (7, 8, 2, 6)
Elements along axis 0 of tensor: 7
Elements along the last axis of tensor: 6
Total number of elements:  672


# Tensor 2 types

 Sparse and Ragged Tensor

In [23]:
tf.rank(c)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [24]:
tf.shape(c)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([7, 8, 2, 6])>

# Indexing in Tensor

In [25]:
sd = tf.constant([345,24,22,6,14,8,66,61])
print(sd.numpy())

[345  24  22   6  14   8  66  61]


In [26]:
print("First:", sd[0].numpy())
print("Last:", sd[-1].numpy())

First: 345
Last: 61


In [27]:
x = tf.constant([[7], [2], [5]])
print(x.shape)
print(x.shape.as_list())


(3, 1)
[3, 1]


In [28]:
reshaped = tf.reshape(x, [1, 3])
print(reshaped.shape)

(1, 3)


In [31]:
matOne = tf.constant([[5,6,7],[1,2,3],[10,9,8]])

matTwo = tf.constant([[1,2,3],[4,5,6],[7,8,9]])

tfMultiply = tf.multiply(matOne,matTwo)

with tf.compat.v1.Session() as session:

	Output = session.run(tfMultiply)

RuntimeError: The Session graph is empty. Add operations to the graph before calling run().